import html2canvas from "html2canvas";
import jsPDF from "jspdf";

interface PDFGeneratorProps {
  element: HTMLElement;
  user: {
    userName?: string;
    userId?: string;
    userEmail?: string;
  } | null;
  progress: {
    cohortName?: string;
  } | null;
  programId?: string;
}

export async function generatePDF({ element, user, progress, programId }: PDFGeneratorProps): Promise<void> {
  // Store original styles
  const originalOverflow = document.body.style.overflow;
  document.body.style.overflow = 'hidden';
  
  const tempDiv = document.createElement('div');
  tempDiv.style.position = 'absolute';
  tempDiv.style.left = '-9999px';
  tempDiv.style.top = '0';
  tempDiv.style.width = `${element.offsetWidth}px`;
  tempDiv.style.backgroundColor = '#ffffff';
  tempDiv.style.zIndex = '9999';
  
  const clone = element.cloneNode(true) as HTMLElement;
  
  const buttons = clone.querySelectorAll('button');
  buttons.forEach(button => button.remove());
  
  const tabs = clone.querySelector('.flex.border-b.mb-6');
  if (tabs) tabs.remove();
  
  const reportHeader = document.createElement('div');
  reportHeader.className = 'mb-6 pb-4 border-b-2 border-blue-600';
  reportHeader.innerHTML = `
    <h1 class="text-2xl font-bold text-blue-800 mb-2">Student Progress Report</h1>
    <div class="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
      <div>
        <p><strong>Student:</strong> ${user?.userName || 'N/A'}</p>
        <p><strong>Student ID:</strong> ${user?.userId || 'N/A'}</p>
        <p><strong>Email:</strong> ${user?.userEmail || 'Not provided'}</p>
      </div>
      <div>
        <p><strong>Cohort:</strong> ${progress?.cohortName || 'N/A'}</p>
        <p><strong>Report Date:</strong> ${new Date().toLocaleDateString()}</p>
        <p><strong>Program:</strong> ${programId || 'N/A'}</p>
      </div>
    </div>
  `;
  
  clone.insertBefore(reportHeader, clone.firstChild);
  
  const reportFooter = document.createElement('div');
  reportFooter.className = 'mt-6 pt-4 border-t text-xs text-gray-500 text-center';
  reportFooter.innerHTML = `
    <p>Generated by Mentor Dashboard • ${new Date().toLocaleString()}</p>
    <p>This report contains confidential student information</p>
  `;
  clone.appendChild(reportFooter);
  
  tempDiv.appendChild(clone);
  document.body.appendChild(tempDiv);
  
  await new Promise<void>((resolve) => {
    const images = clone.getElementsByTagName('img');
    if (images.length === 0) {
      resolve();
      return;
    }
    
    let loadedCount = 0;
    const totalImages = images.length;
    
    const onImageLoad = () => {
      loadedCount++;
      if (loadedCount === totalImages) resolve();
    };
    
    Array.from(images).forEach(img => {
      if (img.complete) {
        loadedCount++;
      } else {
        img.addEventListener('load', onImageLoad);
        img.addEventListener('error', onImageLoad);
      }
    });
    
    if (loadedCount === totalImages) resolve();
  });
  
  await new Promise(resolve => setTimeout(resolve, 1000));
  
  const canvas = await html2canvas(clone, { 
    scale: 2,
    useCORS: true,
    logging: false,
    backgroundColor: "#ffffff",
    width: clone.offsetWidth,
    height: clone.scrollHeight,
    windowWidth: clone.offsetWidth,
    windowHeight: clone.scrollHeight
  });
  
  document.body.removeChild(tempDiv);
  document.body.style.overflow = originalOverflow;
  
  const imgData = canvas.toDataURL("image/png", 1.0);
  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });
  
  const pdfWidth = pdf.internal.pageSize.getWidth();
  const margin = 10;
  const contentWidth = pdfWidth - (margin * 2);
  const contentHeight = (canvas.height * contentWidth) / canvas.width;
  
  let heightLeft = contentHeight;
  
  pdf.addImage(imgData, 'PNG', margin, margin, contentWidth, contentHeight);
  heightLeft -= pdf.internal.pageSize.getHeight() - (margin * 2);
  
  while (heightLeft > 0) {
    const position = heightLeft - contentHeight;
    pdf.addPage();
    pdf.addImage(imgData, 'PNG', margin, position, contentWidth, contentHeight);
    heightLeft -= pdf.internal.pageSize.getHeight() - (margin * 2);
  }
  
  pdf.save(`${(user?.userName || 'student')}_Report_${new Date().toISOString().slice(0, 10)}.pdf`);
}