name: CI/CD - Deploy Mindful Frontend

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::325599888975:role/OIDCRole
          aws-region: ap-south-1

      - name: Install Dependencies (npm)
        working-directory: Mindful_FrontEnd
        run: npm ci

      - name: Download env file
        working-directory: Mindful_FrontEnd
        run: aws s3 cp s3://chippersage-env-prod/mindful/.env .

      - name: Build React App
        working-directory: Mindful_FrontEnd
        run: CI='' npm run build

      - name: Sync to S3
        run: aws s3 sync Mindful_FrontEnd/dist/ s3://chippersage-mindful-frontend-prod --delete

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id E13RRNF0Z7DIB3 --paths "/*"
